FROM ubuntu


USER root

RUN apt-get update && \
    apt install -y software-properties-common && \
    add-apt-repository universe && \
    rm -rf /var/lib/apt/lists/*

RUN apt update && \
    apt install curl -y && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    rm -rf /var/lib/apt/lists/*

RUN apt update && \
    apt upgrade -y && \
    apt install -y ros-humble-desktop && \
    apt install -y ros-dev-tools && \
    rm -rf /var/lib/apt/lists/*

ARG USERNAME
USER $USERNAME
EXPOSE 5901



