#!/usr/bin/env bash
USER=$(id --user --name)
export USER

DISPLAY_NUM=1
while true; do
  if ! xdpyinfo -display :$DISPLAY_NUM >/dev/null 2>&1; then
    if test -f "/tmp/.X$DISPLAY_NUM-lock"; then
	rm "/tmp/.X$DISPLAY_NUM-lock"
    fi
    break
  fi
  ((DISPLAY_NUM++))
done
echo "Using DISPLAY :$DISPLAY_NUM"

RFB_PORT=5900
while true; do
  if ! ss -tulpn | grep $RFB_PORT >/dev/null 2>&1; then
    break
  fi
  ((RFB_PORT++))
done
echo "Using rfb port $RFB_PORT"

unset DISPLAY
Xvnc -rfbauth passwd-file -PasswordFile /home/"$USER"/.config/vnc/passwd -rfbport "$RFB_PORT" -depth 32 -SendPrimary 0 -geometry 1920x1080 :"$DISPLAY_NUM" &
export DISPLAY=:$DISPLAY_NUM
while true; do
        if [ -n "$DISPLAY" ] && xdpyinfo -display "$DISPLAY" >/dev/null 2>&1; then
                echo "DISPLAY is properly set and connected to a display!"
                break
        else
                echo "Waiting for DISPLAY to be properly set and connected to a display..."
                sleep .5
        fi
done
i3
